### ISSUE TITLE
Idea/Suggestion

### ISSUE THREAD

**Issue by WaGi-Coding** [yyuueexxiinngg/BepInEx-Plugins#1]
Hello. It would be great if this mod instead is able to request items from ILS where the slot is set to Remote Supply. Then send a Vessel with the goods to your mecha. I know thats may hard, but it would make much more sense <3

**Comment by yyuueexxiinngg** [comment]
Thanks for your great idea, but I'm not planned to do it, maybe you can share your idea in DSP modding discord server, which can be found here:  [DSP Modding](https://dsp.thunderstore.io/)
