### ISSUE TITLE
Storage Format ID Error

### ISSUE THREAD

**Issue by Benc85** [yyuueexxiinngg/BepInEx-Plugins#2]
Entered 0.59 into box, got this error:

StorageID Format error, should be decimal (FactoryIndex.StorageID)

Everything worked fine last release. 👍

**Comment by Vindicit** [comment]
Same, I cant add any more favorites

**Comment by VenomXII** [comment]
Same here, unable to add any more favorites. I get the same error as reported by @Benc85 
only other mods I have are the updated 5.4.5 Framework and CopyInserters

**Comment by yyuueexxiinngg** [comment]
Fixed in v1.3
