### ISSUE TITLE
关于MOD拉取本地版本号错误的问题

### ISSUE THREAD

**Issue by ChangGengCN** [yyuueexxiinngg/BepInEx-Plugins#4]
不少MOD作者在更新后，没有及时更新代码的版本号，导致错误的提示MOD版本未更新，建议在本地配置文件中增加字段“本地MOD的版本号”，可以手动对当前MOD的版本号进行修改

**Comment by ChangGengCN** [comment]
可以直接在MergedModData.xml中增加两个字段，一个最新版本号，一个本地版本号，默认都是0.0.0.0，MOD运行后自动对本地配置文件更新，方便玩家可以主动修改本地版本号

**Comment by yyuueexxiinngg** [comment]
UI中新增按钮设置使用最新版本号覆盖目前版本号

**Comment by yyuueexxiinngg** [comment]
https://github.com/yyuueexxiinngg/BepInEx-Plugins/commit/4ff3937229c9b0fcdbdea453b77340417b51e633
