### ISSUE TITLE
Not loading with 7.18

### ISSUE THREAD

**Issue by Vindicit** [yyuueexxiinngg/BepInEx-Plugins#6]
I have not played in a bit so I updated to v1.4 and game version 7.18.6940 (and today 7063) but the mod does not load for me at all. Does anyone else have this issue or is it just me?
![2021-06-03 18_20_07-Dyson Sphere Program](https://user-images.githubusercontent.com/79327480/120719784-e02c3a00-c498-11eb-8518-6063e3f0a11c.png)

**Comment by yiweiwang-yw** [comment]
Same error for me

**Comment by yyuueexxiinngg** [comment]
Thanks for providing the log, was received some reports but didn't realize this error.
